### ISSUE TITLE
Disallow ping spoofing

### ISSUE THREAD

**Issue by mbeardwell** [tf2classic/tf2classic-feature-proposals#20]
Some TF2C server hosts are fudging packets so that the client sees a lower latency in the community server browser than they would experience once they had connected and started playing.

**Comment by Technochips** [comment]
Are you talking about disallowing servers from the in-game server browser?

**Comment by abbyslab** [comment]
Probably more likely enforcing stricter conditions on query responses.

On [this](https://github.com/ValveSoftware/Source-1-Games/issues/4484) thread, someone suggests it could be solved by always requiring and checking the challenges. I'm not sure how it's being pulled off because latency is calculated by the client and not sent as data by the server. They thought the servers were resending old packets (which messed up the calculation?).

**Comment by abbyslab** [comment]
I see that this fix may already be applied to TF2. One server owner admitted to doing this in TF2C after a player was experiencing higher latency after connection so I can't explain why it would not be the same for TF2C.

**Comment by Technochips** [comment]
Sorry, that's on Valve's part:. only they have the code of the server browser (it's on the engine side of the game, we don't have access to it) and they're also the one who's hosting the Steam Master Server.
